/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Earning {
  'userId' : Principal,
  'timestamp' : bigint,
  'earningType' : EarningType,
  'amount' : number,
}
export type EarningType = { 'reel' : null } |
  { 'spin' : null } |
  { 'walk' : null };
export interface UserProfile { 'name' : string, 'phoneNumber' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WithdrawalRequest {
  'status' : WithdrawalStatus,
  'method' : { 'upi' : string } |
    { 'bank' : [string, string] },
  'userId' : Principal,
  'timestamp' : bigint,
  'amount' : number,
}
export type WithdrawalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'approveWithdrawal' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getBalanceRequestTokens' : ActorMethod<[], number>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPendingWithdrawals' : ActorMethod<[], Array<WithdrawalRequest>>,
  'getTodaysEarnings' : ActorMethod<[], Array<Earning>>,
  'getUserEarnings' : ActorMethod<[], Array<Earning>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserWithdrawals' : ActorMethod<[], Array<WithdrawalRequest>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'rejectWithdrawal' : ActorMethod<[bigint], undefined>,
  'requestWithdrawal' : ActorMethod<
    [number, { 'upi' : string } | { 'bank' : [string, string] }],
    undefined
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'spinLuckyDraw' : ActorMethod<[], number>,
  'submitSteps' : ActorMethod<[bigint], number>,
  'watchReel' : ActorMethod<[], number>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];