/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'phoneNumber' : IDL.Text,
});
export const WithdrawalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const WithdrawalRequest = IDL.Record({
  'status' : WithdrawalStatus,
  'method' : IDL.Variant({
    'upi' : IDL.Text,
    'bank' : IDL.Tuple(IDL.Text, IDL.Text),
  }),
  'userId' : IDL.Principal,
  'timestamp' : IDL.Int,
  'amount' : IDL.Float64,
});
export const EarningType = IDL.Variant({
  'reel' : IDL.Null,
  'spin' : IDL.Null,
  'walk' : IDL.Null,
});
export const Earning = IDL.Record({
  'userId' : IDL.Principal,
  'timestamp' : IDL.Int,
  'earningType' : EarningType,
  'amount' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'approveWithdrawal' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getBalanceRequestTokens' : IDL.Func([], [IDL.Float64], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPendingWithdrawals' : IDL.Func(
      [],
      [IDL.Vec(WithdrawalRequest)],
      ['query'],
    ),
  'getTodaysEarnings' : IDL.Func([], [IDL.Vec(Earning)], ['query']),
  'getUserEarnings' : IDL.Func([], [IDL.Vec(Earning)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserWithdrawals' : IDL.Func([], [IDL.Vec(WithdrawalRequest)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'rejectWithdrawal' : IDL.Func([IDL.Nat], [], []),
  'requestWithdrawal' : IDL.Func(
      [
        IDL.Float64,
        IDL.Variant({
          'upi' : IDL.Text,
          'bank' : IDL.Tuple(IDL.Text, IDL.Text),
        }),
      ],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'spinLuckyDraw' : IDL.Func([], [IDL.Float64], []),
  'submitSteps' : IDL.Func([IDL.Nat], [IDL.Float64], []),
  'watchReel' : IDL.Func([], [IDL.Float64], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'phoneNumber' : IDL.Text,
  });
  const WithdrawalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const WithdrawalRequest = IDL.Record({
    'status' : WithdrawalStatus,
    'method' : IDL.Variant({
      'upi' : IDL.Text,
      'bank' : IDL.Tuple(IDL.Text, IDL.Text),
    }),
    'userId' : IDL.Principal,
    'timestamp' : IDL.Int,
    'amount' : IDL.Float64,
  });
  const EarningType = IDL.Variant({
    'reel' : IDL.Null,
    'spin' : IDL.Null,
    'walk' : IDL.Null,
  });
  const Earning = IDL.Record({
    'userId' : IDL.Principal,
    'timestamp' : IDL.Int,
    'earningType' : EarningType,
    'amount' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'approveWithdrawal' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getBalanceRequestTokens' : IDL.Func([], [IDL.Float64], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPendingWithdrawals' : IDL.Func(
        [],
        [IDL.Vec(WithdrawalRequest)],
        ['query'],
      ),
    'getTodaysEarnings' : IDL.Func([], [IDL.Vec(Earning)], ['query']),
    'getUserEarnings' : IDL.Func([], [IDL.Vec(Earning)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserWithdrawals' : IDL.Func(
        [],
        [IDL.Vec(WithdrawalRequest)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'rejectWithdrawal' : IDL.Func([IDL.Nat], [], []),
    'requestWithdrawal' : IDL.Func(
        [
          IDL.Float64,
          IDL.Variant({
            'upi' : IDL.Text,
            'bank' : IDL.Tuple(IDL.Text, IDL.Text),
          }),
        ],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'spinLuckyDraw' : IDL.Func([], [IDL.Float64], []),
    'submitSteps' : IDL.Func([IDL.Nat], [IDL.Float64], []),
    'watchReel' : IDL.Func([], [IDL.Float64], []),
  });
};

export const init = ({ IDL }) => { return []; };